name: broken links
on:
  - workflow_call
  - workflow_dispatch
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --base "https://${{ steps.branch-name.outputs.current_branch }}.${{ github.event.repository.name }}" --verbose --no-progress './**/*.html'
          fail: true
